# -*- coding: utf-8 -*-
"""quant-brainteasers-sim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3YYQZ_nNEcSM8RkaJLY-U4B0a24uFYl
"""

# Commented out IPython magic to ensure Python compatibility.
!unzip -q "quant-brainteasers-sim (2).zip"
# %cd "quant-brainteasers-sim"
!pip install -r requirements.txt
!pytest tests/ -v

!jupyter nbconvert --to notebook --execute --inplace notebooks/quant_analysis.ipynb